
all:
	dot -o ../images/query_opt_filter_basic.svg -Tsvg query_opt_filter_basic.dot
	dot -o ../images/query_opt_filter_basic_pop.svg -Tsvg query_opt_filter_basic_pop.dot
	dot -o ../images/query_opt_filter_basic_ig.svg -Tsvg query_opt_filter_basic_ig.dot
	dot -o ../images/query_opt_filter_complex.svg -Tsvg query_opt_filter_complex.dot
	dot -o ../images/query_opt_filter_complex_ig.svg -Tsvg query_opt_filter_complex_ig.dot
	dot -o ../images/o_dmc_configuration_tree.svg -Tsvg o_dmc_configuration_tree.dot
	dot -o ../images/marks_dmc_tree.svg -Tsvg marks_dmc_tree.dot	
	dot -o ../images/marks_dmc_tree_20160125_wibrown.svg -Tsvg marks_dmc_tree_20160125_wibrown.dot
	dot -o ../images/cow_btree_1.svg -Tsvg cow_btree_1.dot
	dot -o ../images/cow_btree_2.svg -Tsvg cow_btree_2.dot
	dot -o ../images/cow_btree_3.svg -Tsvg cow_btree_3.dot

