# Do not use tabs in this file!
repository: https://pagure.io/389-ds-base/

# Required for running on Ruby 1.9
encoding: utf-8

# Change this if we ever need the site to reside in a sub-directory
baseurl: ''

exclude:
  - 'bin'
  # For some reason Openshift 3 installs gems to "bundle" instead of "vendor"
  - 'bundle'
  - 'vendor'
  - 'Gemfile*'
  - 'README.md'
  - 'config.ru'

# The tilde is YAML for nil.  Categories not in this map get nil and placed at the end.
category-order: {usage: 1, developers: 2, design: 3, uncategorized: ~}

permalink: /news/:year/:title.html
paginate: 8
paginate_path: /news/page:num

sass:
  sass_dir: _sass
  style: :compressed

markdown: KramdownPygments
kramdown:
  # Use GitHub flavor markdown
  input: GFM
  hard_wrap: false

# See http://jekyllrb.com/docs/configuration/#frontmatter-defaults
defaults:
  - scope: { path: "docs" }
    values: { layout: "default" }
  - scope: { path: "news" }
    values: { layout: "news" }
  - scope: { path: "_posts" }
    values: { layout: "news" }

plugins:
  - jekyll-sitemap
  - jekyll-paginate
