name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/tmp/src \
        quay.io/389ds/389ds-website-ruby-27:latest \
        /bin/bash -c "chmod -R 777 /tmp/src && bash /usr/libexec/s2i/assemble"
